### ISSUE TITLE
Error on install: dependencies

### ISSUE THREAD

**Issue by eleventhaus** [thenick775/react-ios-pwa-prompt-ts#2]
Error when styled-components isn't also installed

![Screenshot 2023-12-08 at 1 38 14 PM](https://github.com/thenick775/react-ios-pwa-prompt-ts/assets/34343079/a0096649-4b39-49ac-8c07-55d4cc96e46d)

Error resolved after installing styled-components

**Comment by thenick775** [comment]
Yep I have this dep as a peer dependency, so your app can use whatever version of styled components that you bundle.

Will investigate if another solution is preferable!

**Comment by thenick775** [comment]
Citing this reference as I evaluate other options:
[we recommend that you should not bundle and ship styled-components module with your library](https://styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page)

**Comment by thenick775** [comment]
I have come to the conclusion that this is intended behavior, updating readme.

Thank you for opening this issue!
