### ISSUE TITLE
Any way to keep a minimal Install floating button after dismiss?

### ISSUE THREAD

**Issue by mcosti** [thenick775/react-ios-pwa-prompt-ts#4]
Hello, and thank you for this great fork!

At first, I thought permanentlyHideOnDismiss would leave some kind of small floating header/button that would allow the user to see the instructions again, but I don't think that's the case.

Is there any possibility this package could provide that feature?

Thank you

**Comment by thenick775** [comment]
Do you have a UI mock up of what you have in mind (any form will do)? I'll definitely consider something if its non-obtrusive and the layout would work for most applications.

If its not a generic solution that will work by default in most sites, my opinion is a re-prompt label is the duty of the calling application.

Some context:

`permanentlyHideOnDismiss` when set to `false` in this context will still dismiss the prompt until the user refreshes the page, but the prompt will reappear once the user has refreshed.

A potential alternative solution:

I do export the local storage key used, the types used to store the object, as well as all components used.

You can manually reset the values stored in local storage to re-prompt.

Meaning your application could re-prompt using a button, or some other piece of your UI.

Or use the exported components to compose your own prompt with an additional floating label that can manipulate the local storage values.

**Comment by thenick775** [comment]
Looks like I'll need to make some adjustments to make a solution like what's mentioned above work.

Let me see if I can't get a branch going as I wait for your UI mock

**Comment by thenick775** [comment]
@mcosti with version `1.1.0` coming from the PR above you should now be able to accomplish what you need in terms of making your own floating button to re-show the prompt to the user.

You can do this by using the `isOpen` prop on the component to control re-prompting yourself in your application, as well as using `useShouldShowPrompt` or `usePromptStorage` if you need more fine grained control or insight into the values the prompt is using.

See the updated storybook demo for a very basic example of this feature in action, and feel free to let me know if this doesn't give you all that you need 😎 

I went this route as not all applications will agree on where/how the re-prompt button/icon should be implemented, so decided to make it the responsibility of the calling code how it the display and logic of a re-prompt.

I may also add a boolean representing if the user has manually dismissed the prompt in the near future for ease of use.

**Comment by mcosti** [comment]
Hi, @thenick775. That is absolutely amazing.

I feel a bit guilty though, as meanwhile I've managed to release native apps for both iOS and Android, so I cannot make use of this package anymore. (Also, iOS removed PWA support in the 17.4)

**Comment by thenick775** [comment]
For anyone following this issue, and/or worried about PWAs, I'm hopeful that [this](https://9to5mac.com/2024/03/01/apple-home-screen-web-apps-ios-17-eu/) will remain true:


```
Apple says iOS 17.4 won’t remove Home Screen web apps in the EU after all
```
