### ISSUE TITLE
In next.js I get "ReferenceError: window is not defined" when i run dev or build

### ISSUE THREAD

**Issue by cgar420** [thenick775/react-ios-pwa-prompt-ts#7]
⨯ ..\node_modules\react-ios-pwa-prompt-ts\dist\react-ios-pwa-prompt-ts.js (1879:58) @ window

 ⨯ Internal error: ReferenceError: window is not defined
    at Qi (../../../../node_modules/react-ios-pwa-prompt-ts/dist/react-ios-pwa-prompt-ts.js:4093:106)

**Comment by thenick775** [comment]
This library requires use of the browser.

I'm not super familiar with next.js, but are you using a client side component?

**Comment by thenick775** [comment]
Following up on some data based on the following article and thread lead me to believe this is an issue of using context in next, being that your client component is being pre-rendered on the server.

I think this is not an issue with the component library provided here.

Feel free to comment and reopen this issue if it does end up being a problem with this libraries implementation!

Supporting info:
https://blog.sethcorker.com/question/how-to-solve-referenceerror-next-js-window-is-not-defined/
https://stackoverflow.com/a/75692565
